### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kevinch** [stormpath/express-stormpath-angular-sample-project#9]
Hey, i did two tests, locally and on a Heroku app and got the same error on both servers: 

```
Response to preflight request doesn't pass access control check: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:3000' is therefore not allowed access. 
The response had HTTP status code 403.
```
No error in the console though:
```
Initializing Stormpath
Application running at http://localhost:3000
Stormpath Ready
```

Seems to me that i got my credentials right in the `stormpath.yml` and `app.js` files (though it was not easy to figure it out).

Any chance someone got it up and running fine?

The online test is visible [here](https://stormpathexpresstest.herokuapp.com/).

**Comment by mraible** [comment]
You need to specify `http://localhost:3000` as an **Authorized Origin URIs** in your Application's settings.

![screen shot 2017-02-15 at 8 25 21 am](https://cloud.githubusercontent.com/assets/17892/22981067/8b33d820-f358-11e6-93f0-570835354750.png)

**Comment by kevinch** [comment]
Good point. This should be written somewhere in the example repos or more clearly in the docs.
